import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminSupabase } from '@/lib/platformAdmin';

export const dynamic = 'force-dynamic';

const ALLOWED_STATUSES = new Set(['pending', 'approved', 'rejected', 'deferred']);

type CRRow = {
  title: string;
  description?: string | null;
  scope_impact?: string | null;
  cost_impact?: number | null;
  timeline_impact?: string | null;
  approval_status?: string;
  client_visible?: boolean;
};

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> },
) {
  const supabase = await createClient();
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { projectId } = await params;
  const body = await req.json().catch(() => null);
  const { companyId, rows } = (body ?? {}) as { companyId?: string; rows?: CRRow[] };

  if (!companyId || !projectId) {
    return NextResponse.json({ error: 'companyId and projectId are required.' }, { status: 400 });
  }
  if (!Array.isArray(rows) || rows.length === 0) {
    return NextResponse.json({ error: 'rows array is required and must not be empty.' }, { status: 400 });
  }
  if (rows.length > 500) {
    return NextResponse.json({ error: 'Maximum 500 rows per import.' }, { status: 400 });
  }

  const admin = createAdminSupabase();

  const { data: membership } = await admin
    .from('company_users')
    .select('id')
    .eq('auth_user_id', session.user.id)
    .eq('company_id', companyId)
    .eq('status', 'active')
    .maybeSingle();
  if (!membership) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

  const { data: project } = await admin
    .from('projects')
    .select('id')
    .eq('id', projectId)
    .eq('company_id', companyId)
    .maybeSingle();
  if (!project) return NextResponse.json({ error: 'Project not found.' }, { status: 404 });

  // request_number is auto-generated by a DB trigger — insert empty string
  const inserts = rows.map(r => ({
    company_id:      companyId,
    project_id:      projectId,
    request_number:  '',  // DB trigger fills this in
    title:           String(r.title ?? '').trim(),
    description:     r.description ? String(r.description).trim() : null,
    scope_impact:    r.scope_impact ? String(r.scope_impact).trim() : null,
    cost_impact:     typeof r.cost_impact === 'number' ? r.cost_impact
                       : (r.cost_impact ? parseFloat(String(r.cost_impact)) : null),
    timeline_impact: r.timeline_impact ? String(r.timeline_impact).trim() : null,
    approval_status: ALLOWED_STATUSES.has(String(r.approval_status ?? '').toLowerCase())
                       ? String(r.approval_status).toLowerCase()
                       : 'pending',
    client_visible:  r.client_visible === true,
  }));

  const { data, error } = await admin
    .from('change_requests')
    .insert(inserts)
    .select('id');

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({ ok: true, imported: data?.length ?? inserts.length });
}
