import type { NextConfig } from 'next';
import withPWA from '@ducanh2912/next-pwa';

const SECURITY_HEADERS = [
  // Prevent the page from being embedded in an iframe (clickjacking)
  { key: 'X-Frame-Options', value: 'DENY' },
  // Stop browsers sniffing the MIME type
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  // Only send the origin in the Referer header (no full URL)
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  // Enforce HTTPS for 2 years, include subdomains
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  // Disable unnecessary browser features
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=()' },
  // Basic XSS protection for older browsers
  { key: 'X-XSS-Protection', value: '1; mode=block' },
];

const nextConfig: NextConfig = {
  // next-pwa v10 injects a webpack config internally; this empty turbopack key tells
  // Next.js 16 to proceed with Turbopack regardless (the workbox SW is still generated).
  turbopack: {},

  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'nimxzjoqgxzeuxpksdrn.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
    ],
  },

  async headers() {
    return [
      {
        // Apply to all routes
        source: '/(.*)',
        headers: SECURITY_HEADERS,
      },
    ];
  },
};

// PWA wrapper — service worker generated by Workbox into public/
const withPWAConfig = withPWA({
  dest: 'public',
  // Disable the service worker in development to avoid stale-cache confusion
  disable: process.env.NODE_ENV === 'development',
  // Re-fetch page on coming back online
  reloadOnOnline: true,
  // Cache navigations so pages load offline
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
  workboxOptions: {
    disableDevLogs: true,
    // Network-first for Supabase API calls so online always wins but offline still works
    runtimeCaching: [
      {
        urlPattern: /^https:\/\/nimxzjoqgxzeuxpksdrn\.supabase\.co\/.*/i,
        handler: 'NetworkFirst',
        options: {
          cacheName: 'supabase-api-cache',
          expiration: {
            maxEntries: 64,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          },
          networkTimeoutSeconds: 10,
        },
      },
    ],
  },
});

export default withPWAConfig(nextConfig);
